/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Viewer;

import DataBase.DataBaseArrays;
import Entities.Clientes;
import Services.ClientesCodec;
import Services.LeitorEEscritor;
import java.awt.Color;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jpaul
 */
public class ClientesViewer extends javax.swing.JPanel {
    private String Tipo;
    
    File Path = new File("ArquivosTXT/Clientes.txt");
    
    public ClientesViewer() {
        initComponents();
        TabelaClientes.setSelectionBackground(new Color(255, 180, 210)); 
        TabelaClientes.setSelectionForeground(Color.BLACK); 
        TabelaClientes.setDefaultEditor(Object.class, null);
        DataBaseArrays.setArrayClientes(LeitorEEscritor.Ler(Path,new ClientesCodec()));
        carregarTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomeClienteLabel = new javax.swing.JLabel();
        CelularTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        ClienteTextField = new javax.swing.JTextField();
        CelularLabel = new javax.swing.JLabel();
        CPFLabel = new javax.swing.JLabel();
        CPFTextField = new javax.swing.JTextField();
        EnderecoTextField = new javax.swing.JTextField();
        EnderecoLabel = new javax.swing.JLabel();
        NovoButton = new javax.swing.JButton();
        EditarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        SalvarButton = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel3 = new javax.swing.JPanel();
        ConsultaTextField = new javax.swing.JTextField();
        PesquisarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultaArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 244, 208));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);

        jToolBar2.setBackground(new java.awt.Color(255, 251, 242));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(255, 251, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setForeground(new java.awt.Color(255, 251, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 450));

        jLabel1.setBackground(new java.awt.Color(234, 2, 127));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Clientes");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(234, 2, 127));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PETS ICON MAIS CLARO.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(234, 2, 127));
        jSeparator1.setForeground(new java.awt.Color(234, 2, 127));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 42, 12));
        jLabel3.setText("Dados do Cliente");

        jLabel4.setForeground(new java.awt.Color(255, 251, 242));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1 (2).png"))); // NOI18N

        NomeClienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        NomeClienteLabel.setForeground(new java.awt.Color(126, 42, 12));
        NomeClienteLabel.setText("Nome do Cliente");

        CelularTextField.setBackground(new java.awt.Color(255, 255, 255));
        CelularTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CelularTextField.setEnabled(false);
        CelularTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelularTextFieldActionPerformed(evt);
            }
        });

        TabelaClientes.setAutoCreateRowSorter(true);
        TabelaClientes.setBackground(new java.awt.Color(255, 255, 255));
        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Celular", "Endereço"
            }
        ));
        TabelaClientes.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaClientes);

        ClienteTextField.setBackground(new java.awt.Color(255, 255, 255));
        ClienteTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        ClienteTextField.setEnabled(false);
        ClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTextFieldActionPerformed(evt);
            }
        });

        CelularLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CelularLabel.setForeground(new java.awt.Color(126, 42, 12));
        CelularLabel.setText("Celular");

        CPFLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        CPFLabel.setForeground(new java.awt.Color(126, 42, 12));
        CPFLabel.setText("CPF do tutor");

        CPFTextField.setBackground(new java.awt.Color(255, 255, 255));
        CPFTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CPFTextField.setEnabled(false);

        EnderecoTextField.setBackground(new java.awt.Color(255, 255, 255));
        EnderecoTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        EnderecoTextField.setEnabled(false);
        EnderecoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnderecoTextFieldActionPerformed(evt);
            }
        });

        EnderecoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EnderecoLabel.setForeground(new java.awt.Color(126, 42, 12));
        EnderecoLabel.setText("Endereço");

        NovoButton.setBackground(new java.awt.Color(236, 14, 131));
        NovoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NovoButton.setForeground(new java.awt.Color(255, 255, 255));
        NovoButton.setText("Novo");
        NovoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoButtonActionPerformed(evt);
            }
        });

        EditarButton.setBackground(new java.awt.Color(236, 14, 131));
        EditarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditarButton.setForeground(new java.awt.Color(255, 255, 255));
        EditarButton.setText("Editar");
        EditarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setBackground(new java.awt.Color(236, 14, 131));
        ExcluirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExcluirButton.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirButton.setText("Excluir");
        ExcluirButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        CancelarButton.setBackground(new java.awt.Color(236, 14, 131));
        CancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarButton.setText("Cancelar");
        CancelarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelarButton.setVisible(false);
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        SalvarButton.setBackground(new java.awt.Color(236, 14, 131));
        SalvarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalvarButton.setForeground(new java.awt.Color(255, 255, 255));
        SalvarButton.setText("Salvar");
        SalvarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvarButton.setVisible(false);
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ClienteTextField)
                            .addComponent(NomeClienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnderecoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(EnderecoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(SalvarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CelularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CPFLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                .addComponent(CPFTextField)
                                .addComponent(CelularTextField))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NovoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeClienteLabel)
                    .addComponent(CelularLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CelularTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(EnderecoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovoButton)
                    .addComponent(EditarButton)
                    .addComponent(ExcluirButton)
                    .addComponent(CancelarButton)
                    .addComponent(SalvarButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar2.add(jPanel2);

        jToolBar3.setRollover(true);

        jPanel3.setBackground(new java.awt.Color(255, 251, 242));
        jPanel3.setForeground(new java.awt.Color(255, 251, 242));

        ConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1)));
        ConsultaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaTextFieldActionPerformed(evt);
            }
        });

        PesquisarButton.setBackground(new java.awt.Color(236, 14, 131));
        PesquisarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PesquisarButton.setForeground(new java.awt.Color(255, 255, 255));
        PesquisarButton.setText("Pesquisar");
        PesquisarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PesquisarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarButtonActionPerformed(evt);
            }
        });

        ConsultaArea.setColumns(20);
        ConsultaArea.setRows(5);
        jScrollPane1.setViewportView(ConsultaArea);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(126, 42, 12));
        jLabel5.setText("Digite o CPF do Cliente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PesquisarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTextFieldActionPerformed

    private void EnderecoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoTextFieldActionPerformed

    private void ConsultaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaTextFieldActionPerformed

    private void CelularTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelularTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelularTextFieldActionPerformed

    private void NovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoButtonActionPerformed
        HabilitarBotao(true);
        Tipo = "novo";
        HabilitarTextField(true);
        limparCampos();
        ClienteTextField.requestFocus();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_NovoButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        limparCampos();
        HabilitarBotao(false);
        HabilitarTextField(false);
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void EditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarButtonActionPerformed
        HabilitarBotao(true);
        Tipo = "editar";
        HabilitarTextField(true);
        ClienteTextField.requestFocus();
    }//GEN-LAST:event_EditarButtonActionPerformed
    
    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
        if(ClienteTextField.getText().trim().isEmpty() || CPFTextField.getText().trim().isEmpty() || EnderecoTextField.getText().trim().isEmpty() || CelularTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campos Vazio, digite algo!", "Campos Vazios",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            if(Tipo.equals("novo")){
                String Nome = ClienteTextField.getText().trim();
                String CPF = CPFTextField.getText().trim();
                String Endereco = EnderecoTextField.getText().trim();
                String Celular = CelularTextField.getText().trim();
                DataBaseArrays.ArrayClientes.add(new Clientes(Nome,Celular,CPF,Endereco));
                LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayClientes , new ClientesCodec(), true);
                carregarTabela();
                limparCampos();
                HabilitarBotao(false);
                HabilitarTextField(false);
            }
            else if(Tipo.equals("editar")){
                int linha = TabelaClientes.getSelectedRow();
                if(linha != -1){
                    String Nome = ClienteTextField.getText();
                    String CPF = CPFTextField.getText();
                    String Endereco = EnderecoTextField.getText();
                    String Celular = CelularTextField.getText();
                    DataBaseArrays.ArrayClientes.set(linha, new Clientes(Nome,Celular,CPF,Endereco));
                    LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayClientes , new ClientesCodec(), false);
                    carregarTabela();
                    limparCampos();
                    HabilitarTextField(false);
                    HabilitarBotao(false);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Selecione uma linha", "Selecione uma linha para editar!",JOptionPane.WARNING_MESSAGE);
                }
            }
        }    
    }//GEN-LAST:event_SalvarButtonActionPerformed

    private void TabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClientesMouseClicked
        int linha = TabelaClientes.getSelectedRow();
        if (linha != -1) {
            ClienteTextField.setText(TabelaClientes.getValueAt(linha, 0).toString());
            CPFTextField.setText(TabelaClientes.getValueAt(linha, 1).toString());
            CelularTextField.setText(TabelaClientes.getValueAt(linha, 2).toString());
            EnderecoTextField.setText(TabelaClientes.getValueAt(linha, 3).toString());
        }
    }//GEN-LAST:event_TabelaClientesMouseClicked

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Deseja Excluir?","Confirmação",JOptionPane.YES_NO_OPTION);
        if(Confirmacao == JOptionPane.YES_OPTION){
            int linha = TabelaClientes.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) TabelaClientes.getModel();
            DataBaseArrays.ArrayClientes.remove(linha);
            model.removeRow(linha);
            LeitorEEscritor.Escrever(Path, DataBaseArrays.ArrayClientes, new ClientesCodec(), false);
            limparCampos();
        }
        
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void PesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarButtonActionPerformed
        ConsultaArea.setText("");
        for(Clientes a : DataBaseArrays.ArrayClientes){
        if(a.getCPF().equals(ConsultaTextField.getText())){
            ConsultaArea.setText(a.toString());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisarButtonActionPerformed
    
    private void limparCampos(){
        CPFTextField.setText("");
        CelularTextField.setText("");
        EnderecoTextField.setText("");
        ClienteTextField.setText("");
    
    
    }
    
    private void HabilitarBotao(boolean a){
        SalvarButton.setVisible(a);
        CancelarButton.setVisible(a);
        NovoButton.setVisible(!a);
        EditarButton.setVisible(!a);
        ExcluirButton.setVisible(!a);
    }
    
    private void carregarTabela() {
    DefaultTableModel model = (DefaultTableModel) TabelaClientes.getModel();
    model.setRowCount(0); 

    for (Clientes c : DataBaseArrays.ArrayClientes) {
        model.addRow(new Object[]{
            c.getNome(),
            c.getCPF(),
            c.getCelular(),
            c.getEndereco()
            
        });
    }
}

    private void HabilitarTextField(boolean a){
    ClienteTextField.setEnabled(a);
    CelularTextField.setEnabled(a);
    CPFTextField.setEnabled(a);
    EnderecoTextField.setEnabled(a);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JTextField CPFTextField;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JLabel CelularLabel;
    private javax.swing.JTextField CelularTextField;
    private javax.swing.JTextField ClienteTextField;
    private javax.swing.JTextArea ConsultaArea;
    private javax.swing.JTextField ConsultaTextField;
    private javax.swing.JButton EditarButton;
    private javax.swing.JLabel EnderecoLabel;
    private javax.swing.JTextField EnderecoTextField;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JLabel NomeClienteLabel;
    private javax.swing.JButton NovoButton;
    private javax.swing.JButton PesquisarButton;
    private javax.swing.JButton SalvarButton;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
