/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Viewer;
import Entities.Usuario;
import Services.LeitorEEscritor;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import Services.UsuariosCodec;
import java.io.File;

/**
 *
 * @author jpaul
 */
public class LoginView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());
    File Path = new File("ArquivosTXT/Usuarios_codigo.txt");
    /**
     * Creates new form NewJFrame
     */
    public LoginView() {
       
        FlatLightLaf.setup();
        //CAIXA DE TEXTO
        UIManager.put("OptionPane.background", new Color(255,251,242));
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", new Color(126,42,12));
        UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 12));
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EntrarButton = new javax.swing.JButton();
        UsuarioTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        UsuarioLabel = new javax.swing.JLabel();
        Texto2Label = new javax.swing.JLabel();
        Texto1Label = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        IconLabel = new javax.swing.JLabel();
        BackGroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetShop Pet&Love");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(
            getClass().getResource("/imagem/logo_paw_orange.png")
        )
    );
    setMinimumSize(new java.awt.Dimension(800, 550));
    setResizable(false);
    setSize(new java.awt.Dimension(800, 550));
    getContentPane().setLayout(null);

    jPanel1.setBackground(new java.awt.Color(255, 251, 242));
    jPanel1.setFocusable(false);
    jPanel1.setName("PetShop Tazmania"); // NOI18N
    jPanel1.setLayout(null);

    EntrarButton.setBackground(new java.awt.Color(234, 2, 127));
    EntrarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    EntrarButton.setForeground(new java.awt.Color(255, 255, 255));
    EntrarButton.setText("Entrar no Sistema");
    EntrarButton.setBorder(null);
    EntrarButton.setBorderPainted(false);
    EntrarButton.setFocusPainted(false);
    EntrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            EntrarButtonMouseEntered(evt);
        }
    });
    EntrarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            EntrarButtonActionPerformed(evt);
        }
    });
    jPanel1.add(EntrarButton);
    EntrarButton.setBounds(23, 312, 303, 45);

    UsuarioTextField.setBackground(new java.awt.Color(255, 255, 255));
    UsuarioTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
    UsuarioTextField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
    UsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            UsuarioTextFieldActionPerformed(evt);
        }
    });
    jPanel1.add(UsuarioTextField);
    UsuarioTextField.setBounds(23, 168, 303, 40);

    PasswordTextField.setBackground(new java.awt.Color(255, 255, 255));
    PasswordTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 210, 164), 2), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
    PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PasswordTextFieldActionPerformed(evt);
        }
    });
    jPanel1.add(PasswordTextField);
    PasswordTextField.setBounds(23, 246, 303, 40);

    UsuarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    UsuarioLabel.setForeground(new java.awt.Color(126, 42, 12));
    UsuarioLabel.setText("Usuário");
    jPanel1.add(UsuarioLabel);
    UsuarioLabel.setBounds(23, 142, 303, 20);

    Texto2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Texto2Label.setForeground(new java.awt.Color(126, 42, 12));
    Texto2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Texto2Label.setText("Entre com suas credenciais para acessar o sistema");
    jPanel1.add(Texto2Label);
    Texto2Label.setBounds(6, 110, 338, 14);

    Texto1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Texto1Label.setForeground(new java.awt.Color(126, 42, 12));
    Texto1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    Texto1Label.setText("Bem-vindo de volta!");
    jPanel1.add(Texto1Label);
    Texto1Label.setBounds(0, 90, 350, 14);

    SenhaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    SenhaLabel.setForeground(new java.awt.Color(126, 42, 12));
    SenhaLabel.setText("Senha");
    jPanel1.add(SenhaLabel);
    SenhaLabel.setBounds(23, 220, 40, 20);

    IconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/ICON.png"))); // NOI18N
    jPanel1.add(IconLabel);
    IconLabel.setBounds(0, 20, 350, 60);

    getContentPane().add(jPanel1);
    jPanel1.setBounds(225, 70, 350, 375);

    BackGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Design sem nome (3)_1.png"))); // NOI18N
    BackGroundLabel.setIconTextGap(0);
    getContentPane().add(BackGroundLabel);
    BackGroundLabel.setBounds(0, 0, 800, 550);

    setSize(new java.awt.Dimension(816, 559));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void UsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextFieldActionPerformed

    private void EntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonActionPerformed
        if(UsuarioTextField.getText().isEmpty() || PasswordTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos Vazios: Insira seu login ","Login Vazio",JOptionPane.ERROR_MESSAGE);
            
        }
        else if(ValidarSenha(UsuarioTextField.getText().toLowerCase(),PasswordTextField.getText()) == true){
            this.dispose();
            MenuJframe Menu = new MenuJframe();
            Menu.setLocationRelativeTo(null);
            Menu.setVisible(true);
        }
        else{
            UsuarioTextField.setText("");
            PasswordTextField.setText("");
            JOptionPane.showMessageDialog(null, "Senha incorreta: Tente Novamente","Login Incorreto",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_EntrarButtonActionPerformed

    private void EntrarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarButtonMouseEntered
                // TODO add your handling code here:        
    }//GEN-LAST:event_EntrarButtonMouseEntered

    private boolean ValidarSenha(String Usuario,String Senha){
        
        LeitorEEscritor.Ler(Path, new UsuariosCodec());
        for(Usuario u : LeitorEEscritor.Ler(Path, new UsuariosCodec()) ){
            if(u.getLoginUsuario().toLowerCase().equals(Usuario)  && u.getLoginSenha().equals(Senha)){
                return true;
            }
        }
        return false;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLabel;
    private javax.swing.JButton EntrarButton;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel Texto1Label;
    private javax.swing.JLabel Texto2Label;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JTextField UsuarioTextField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
