/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Viewer;

import DataBase.DataBaseArrays;
import Entities.Clientes;
import Entities.Pets;
import Services.ClientesCodec;
import Services.LeitorEEscritor;
import Services.PetsCodec;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.nio.file.Path;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jpaul
 */
public class PetsViewer extends javax.swing.JPanel {
    
    
    
    File Path = new File("ArquivosTXT/Pets.txt");
    private String Tipo;
    /**
     * Creates new form ClientesViewer
     */
    public PetsViewer() {
        initComponents();   
        UIManager.put("OptionPane.background", new Color(255,251,242));
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", new Color(126,42,12));
        UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 12));
        limparCampos();
        TabelaPets.setSelectionBackground(new Color(255, 180, 210)); 
        TabelaPets.setSelectionForeground(Color.BLACK); 
        TabelaPets.setDefaultEditor(Object.class, null);
        UIManager.put("ComboBox.buttonBackground", new Color(255,255,255));

         DataBaseArrays.setArrayPets(LeitorEEscritor.Ler(Path,new PetsCodec()));
         carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SexoButton = new javax.swing.ButtonGroup();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RacaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaPets = new javax.swing.JTable();
        NomeTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EspecieComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CPFTextField = new javax.swing.JTextField();
        SexoLabel = new javax.swing.JLabel();
        IdadeTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MachoRadioButton = new javax.swing.JRadioButton();
        FemeaRadioButton = new javax.swing.JRadioButton();
        EditarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        SalvarButton = new javax.swing.JButton();
        NovoButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        ConsultaTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultaArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 244, 208));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setFocusable(false);
        setRequestFocusEnabled(false);

        jToolBar2.setBackground(new java.awt.Color(255, 251, 242));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setRollover(true);

        jPanel1.setBackground(new java.awt.Color(255, 251, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(255, 251, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 450));

        jLabel1.setBackground(new java.awt.Color(234, 2, 127));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Pets");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(234, 2, 127));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PETS ICON MAIS CLARO.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(234, 2, 127));
        jSeparator1.setForeground(new java.awt.Color(234, 2, 127));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 42, 12));
        jLabel3.setText("Dados do Pet");

        jLabel4.setForeground(new java.awt.Color(255, 251, 242));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1 (2).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(126, 42, 12));
        jLabel5.setText("Nome do Pet");

        RacaTextField.setBackground(new java.awt.Color(255, 255, 255));
        RacaTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        RacaTextField.setEnabled(false);

        TabelaPets.setAutoCreateRowSorter(true);
        TabelaPets.setBackground(new java.awt.Color(255, 255, 255));
        TabelaPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Raça", "Idade", "Espécie", "CPF do tutor", "Sexo"
            }
        ));
        TabelaPets.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TabelaPets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPetsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaPets);

        NomeTextField.setBackground(new java.awt.Color(255, 255, 255));
        NomeTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        NomeTextField.setEnabled(false);
        NomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(126, 42, 12));
        jLabel6.setText("Espécie");

        EspecieComboBox.setBackground(new java.awt.Color(255, 255, 255));
        EspecieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cachorro", "Gato", "Passaro", "Roedor" }));
        EspecieComboBox.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1)));
        EspecieComboBox.setEnabled(false);
        EspecieComboBox.setFocusable(false);
        EspecieComboBox.setRequestFocusEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(126, 42, 12));
        jLabel11.setText("Raça");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(126, 42, 12));
        jLabel7.setText("CPF do tutor");

        CPFTextField.setBackground(new java.awt.Color(255, 255, 255));
        CPFTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CPFTextField.setEnabled(false);

        SexoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SexoLabel.setForeground(new java.awt.Color(126, 42, 12));
        SexoLabel.setText("Sexo");

        IdadeTextField.setBackground(new java.awt.Color(255, 255, 255));
        IdadeTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        IdadeTextField.setEnabled(false);
        IdadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdadeTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(126, 42, 12));
        jLabel13.setText("Idade");

        SexoButton.add(MachoRadioButton);
        MachoRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MachoRadioButton.setForeground(new java.awt.Color(126, 42, 12));
        MachoRadioButton.setText("Macho");
        MachoRadioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        MachoRadioButton.setEnabled(false);
        MachoRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MachoRadioButtonActionPerformed(evt);
            }
        });

        SexoButton.add(FemeaRadioButton);
        FemeaRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FemeaRadioButton.setForeground(new java.awt.Color(126, 42, 12));
        FemeaRadioButton.setText("Fêmea");
        FemeaRadioButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        FemeaRadioButton.setEnabled(false);
        FemeaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeaRadioButtonActionPerformed(evt);
            }
        });

        EditarButton.setBackground(new java.awt.Color(236, 14, 131));
        EditarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditarButton.setForeground(new java.awt.Color(255, 255, 255));
        EditarButton.setText("Editar");
        EditarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setBackground(new java.awt.Color(236, 14, 131));
        ExcluirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExcluirButton.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirButton.setText("Excluir");
        ExcluirButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        SalvarButton.setBackground(new java.awt.Color(236, 14, 131));
        SalvarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalvarButton.setForeground(new java.awt.Color(255, 255, 255));
        SalvarButton.setText("Salvar");
        SalvarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvarButton.setVisible(false);
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        NovoButton.setBackground(new java.awt.Color(236, 14, 131));
        NovoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NovoButton.setForeground(new java.awt.Color(255, 255, 255));
        NovoButton.setText("Novo");
        NovoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoButtonActionPerformed(evt);
            }
        });

        CancelarButton.setBackground(new java.awt.Color(236, 14, 131));
        CancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarButton.setText("Cancelar");
        CancelarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelarButton.setVisible(false);
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RacaTextField)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdadeTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NovoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EspecieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MachoRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FemeaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspecieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RacaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(SexoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IdadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EditarButton)
                            .addComponent(ExcluirButton)
                            .addComponent(SalvarButton)
                            .addComponent(NovoButton)
                            .addComponent(CancelarButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MachoRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FemeaRadioButton)
                        .addGap(38, 38, 38)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel1);

        jToolBar3.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(255, 251, 242));
        jPanel2.setForeground(new java.awt.Color(255, 251, 242));

        ConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1)));
        ConsultaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaTextFieldActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(236, 14, 131));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pesquisar");
        jButton5.setToolTipText("");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ConsultaArea.setColumns(20);
        ConsultaArea.setRows(5);
        jScrollPane1.setViewportView(ConsultaArea);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(126, 42, 12));
        jLabel8.setText("Digite o CPF do Tutor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IdadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdadeTextFieldActionPerformed

    private void MachoRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MachoRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MachoRadioButtonActionPerformed

    private void NomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTextFieldActionPerformed

    private void FemeaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeaRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeaRadioButtonActionPerformed

    private void ConsultaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaTextFieldActionPerformed

    private void NovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoButtonActionPerformed
    HabilitarBotao(true);
    HabilitarCampos(true);
    Tipo = "novo";
    limparCampos();
    NomeTextField.requestFocus();
    }//GEN-LAST:event_NovoButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
    limparCampos();
    HabilitarBotao(false);
    HabilitarCampos(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Deseja Excluir?","Confirmação",JOptionPane.YES_NO_OPTION);
        if(Confirmacao == JOptionPane.YES_OPTION){
            int linha = TabelaPets.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) TabelaPets.getModel();
            DataBaseArrays.ArrayPets.remove(linha);
            model.removeRow(linha);
            LeitorEEscritor.Escrever(Path, DataBaseArrays.ArrayPets, new PetsCodec(), false);
            limparCampos();
        }// TODO add your handling code here:
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
        try{
            if(NomeTextField.getText().trim().isEmpty() || CPFTextField.getText().trim().isEmpty() || IdadeTextField.getText().trim().isEmpty() || RacaTextField.getText().trim().isEmpty() || EspecieComboBox.getSelectedIndex() == -1 || (!MachoRadioButton.isSelected() && !FemeaRadioButton.isSelected())){
                JOptionPane.showMessageDialog(null,"Campos Vazio, digite algo!", "Campos Vazios",JOptionPane.WARNING_MESSAGE);
            }
            else{
            
                if(Tipo.equals("novo")){
                    String Nome = NomeTextField.getText().trim();
                    String CPF = CPFTextField.getText().trim();
                    int idade = Integer.parseInt(IdadeTextField.getText().trim());
                    String Raca = RacaTextField.getText().trim();
                    String Especie = (String) EspecieComboBox.getSelectedItem();
                    String Sexo = SetandoSexo();
                    DataBaseArrays.ArrayPets.add(new Pets(Nome,Raca,idade,Especie,CPF,Sexo));
                    LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayPets , new PetsCodec(), true);
                    carregarTabela();
                    limparCampos();
                    HabilitarBotao(false);
                    HabilitarCampos(false);
                }
                else if(Tipo.equals("editar")){
                    int linha = TabelaPets.getSelectedRow();
                    if(linha != -1){
                        String Nome = NomeTextField.getText().trim();
                        String CPF = CPFTextField.getText().trim();
                        int idade = Integer.parseInt(IdadeTextField.getText().trim());
                        String Raca = RacaTextField.getText().trim();
                        String Especie = (String) EspecieComboBox.getSelectedItem();
                        String Sexo = SetandoSexo();
                        DataBaseArrays.ArrayPets.set(linha, new Pets(Nome,Raca,idade,Especie,CPF,Sexo));
                        LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayPets , new PetsCodec(), false);
                        carregarTabela();
                        limparCampos();
                        HabilitarCampos(false);
                        HabilitarBotao(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Selecione uma linha para editar!", "Selecione uma linha",JOptionPane.WARNING_MESSAGE);
                    }
                }
            
            } 
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite um numero na idade!","ERROR: Caracter Invalido",JOptionPane.WARNING_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_SalvarButtonActionPerformed

    private void TabelaPetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPetsMouseClicked
        int linha = TabelaPets.getSelectedRow();
        if (linha != -1) {
            NomeTextField.setText(TabelaPets.getValueAt(linha, 0).toString());
            RacaTextField.setText(TabelaPets.getValueAt(linha, 1).toString());
            IdadeTextField.setText(TabelaPets.getValueAt(linha, 2).toString());
            EspecieComboBox.setSelectedIndex(SelecionarEspecie(TabelaPets.getValueAt(linha,3).toString()));
            CPFTextField.setText(TabelaPets.getValueAt(linha, 4).toString());
            SelecionarSexo(TabelaPets.getValueAt(linha, 5).toString());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaPetsMouseClicked

    
    private void EditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarButtonActionPerformed
         HabilitarBotao(true);
        HabilitarCampos(true);
        Tipo = "editar";
        NomeTextField.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_EditarButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConsultaArea.setText("");
        for(Pets a : DataBaseArrays.ArrayPets){
        if(a.getTutor().equals(ConsultaTextField.getText())){
            ConsultaArea.setText(a.toString());
        }
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void limparCampos(){
        CPFTextField.setText("");
        RacaTextField.setText("");
        NomeTextField.setText("");
        IdadeTextField.setText("");
        SexoButton.clearSelection();
        EspecieComboBox.setSelectedIndex(-1);
    }
    
    private void HabilitarBotao(boolean a){
        SalvarButton.setVisible(a);
        CancelarButton.setVisible(a);
        NovoButton.setVisible(!a);
        EditarButton.setVisible(!a);
        ExcluirButton.setVisible(!a);
    }
    
    private void HabilitarCampos(boolean a){
    NomeTextField.setEnabled(a);
    RacaTextField.setEnabled(a);
    CPFTextField.setEnabled(a);
    IdadeTextField.setEnabled(a);
    FemeaRadioButton.setEnabled(a);
    MachoRadioButton.setEnabled(a);
    EspecieComboBox.setEnabled(a);
    }
    
    private void carregarTabela() {
    DefaultTableModel model = (DefaultTableModel) TabelaPets.getModel();
    model.setRowCount(0); 

    for (Pets c : DataBaseArrays.ArrayPets) {
        model.addRow(new Object[]{
            c.getNome(),
            c.getRaca(),
            c.getIdade(),
            c.getEspecie(),
            c.getTutor(),
            c.getSexo()
            
        });
    }
}
    
    private int SelecionarEspecie(String a){
    if(a.equals("Cachorro")){
        return 0;
    }
    else if(a.equals("Gato")){
        return 1;
    }
    else if(a.equals("Passaro")){
        return 2;
    }
    else{
        return 3;
    }
    
    }
    
    private void SelecionarSexo(String a){
        if (a.equals("Macho")) {
            MachoRadioButton.setSelected(true);
        } 
        else {
            FemeaRadioButton.setSelected(true);
        }   
    }
    
    private String SetandoSexo(){
    if (MachoRadioButton.isSelected()) {
            return "Macho";
        } 
    else if(FemeaRadioButton.isSelected()){
            return "Femea";
        }
    return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPFTextField;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JTextArea ConsultaArea;
    private javax.swing.JTextField ConsultaTextField;
    private javax.swing.JButton EditarButton;
    private javax.swing.JComboBox<String> EspecieComboBox;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JRadioButton FemeaRadioButton;
    private javax.swing.JTextField IdadeTextField;
    private javax.swing.JRadioButton MachoRadioButton;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JButton NovoButton;
    private javax.swing.JTextField RacaTextField;
    private javax.swing.JButton SalvarButton;
    private javax.swing.ButtonGroup SexoButton;
    private javax.swing.JLabel SexoLabel;
    private javax.swing.JTable TabelaPets;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
