/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Viewer;

import DataBase.DataBaseArrays;
import Entities.Clientes;
import Entities.Produtos;
import Services.LeitorEEscritor;
import Services.ProdutoCodec;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jpaul
 */
public class ProdutosViewer extends javax.swing.JPanel {
    
    
    
    File Path = new File("ArquivosTXT/Produtos.txt");
    private String Tipo;
    /**
     * Creates new form ClientesViewer
     */
    public ProdutosViewer() {
        initComponents();   
        UIManager.put("OptionPane.background", new Color(255,251,242));
        UIManager.put("Panel.background", Color.DARK_GRAY);
        UIManager.put("OptionPane.messageForeground", new Color(126,42,12));
        UIManager.put("OptionPane.messageFont", new Font("Segoe UI", Font.BOLD, 12));
        limparCampos();
        TabelaProdutos.setSelectionBackground(new Color(255, 180, 210)); 
        TabelaProdutos.setSelectionForeground(Color.BLACK); 
        TabelaProdutos.setDefaultEditor(Object.class, null);
        UIManager.put("ComboBox.buttonBackground", new Color(255,255,255));

         DataBaseArrays.setArrayProdutos(LeitorEEscritor.Ler(Path,new ProdutoCodec()));
         carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SexoButton = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TipoComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        ValorTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EditarButton = new javax.swing.JButton();
        ExcluirButton = new javax.swing.JButton();
        SalvarButton = new javax.swing.JButton();
        NovoButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        NomeTextField = new javax.swing.JTextField();
        CodigoTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        QuantidadeTextField = new javax.swing.JTextField();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        ConsultaTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultaArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(255, 244, 208));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setFocusable(false);
        setRequestFocusEnabled(false);

        jToolBar2.setBackground(new java.awt.Color(255, 251, 242));
        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setRollover(true);

        jPanel1.setBackground(new java.awt.Color(255, 251, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.setForeground(new java.awt.Color(255, 251, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 450));

        jLabel1.setBackground(new java.awt.Color(234, 2, 127));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produtos");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(234, 2, 127));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/PETS ICON MAIS CLARO.png"))); // NOI18N
        jLabel2.setOpaque(true);

        jSeparator1.setBackground(new java.awt.Color(234, 2, 127));
        jSeparator1.setForeground(new java.awt.Color(234, 2, 127));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 42, 12));
        jLabel3.setText("Dados do Produto");

        jLabel4.setForeground(new java.awt.Color(255, 251, 242));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/1 (2).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(126, 42, 12));
        jLabel5.setText("Código do Produto");

        TabelaProdutos.setAutoCreateRowSorter(true);
        TabelaProdutos.setBackground(new java.awt.Color(255, 255, 255));
        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Tipo ", "Valor", "Quantidade"
            }
        ));
        TabelaProdutos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        TabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaProdutos);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(126, 42, 12));
        jLabel6.setText("Tipo do Produto");

        TipoComboBox.setBackground(new java.awt.Color(255, 255, 255));
        TipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ração", "Brinquedo", "Acessório", "Item de Higiene" }));
        TipoComboBox.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 3, 1, 1)));
        TipoComboBox.setEnabled(false);
        TipoComboBox.setFocusable(false);
        TipoComboBox.setRequestFocusEnabled(false);
        TipoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(126, 42, 12));
        jLabel11.setText("Quantidade");

        ValorTextField.setBackground(new java.awt.Color(255, 255, 255));
        ValorTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        ValorTextField.setEnabled(false);
        ValorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTextFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(126, 42, 12));
        jLabel13.setText("Valor do Produto");

        EditarButton.setBackground(new java.awt.Color(236, 14, 131));
        EditarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditarButton.setForeground(new java.awt.Color(255, 255, 255));
        EditarButton.setText("Editar");
        EditarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarButtonActionPerformed(evt);
            }
        });

        ExcluirButton.setBackground(new java.awt.Color(236, 14, 131));
        ExcluirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExcluirButton.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirButton.setText("Excluir");
        ExcluirButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        SalvarButton.setBackground(new java.awt.Color(236, 14, 131));
        SalvarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SalvarButton.setForeground(new java.awt.Color(255, 255, 255));
        SalvarButton.setText("Salvar");
        SalvarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalvarButton.setVisible(false);
        SalvarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarButtonActionPerformed(evt);
            }
        });

        NovoButton.setBackground(new java.awt.Color(236, 14, 131));
        NovoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NovoButton.setForeground(new java.awt.Color(255, 255, 255));
        NovoButton.setText("Novo");
        NovoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoButtonActionPerformed(evt);
            }
        });

        CancelarButton.setBackground(new java.awt.Color(236, 14, 131));
        CancelarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarButton.setText("Cancelar");
        CancelarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelarButton.setVisible(false);
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        NomeTextField.setBackground(new java.awt.Color(255, 255, 255));
        NomeTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        NomeTextField.setEnabled(false);
        NomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextFieldActionPerformed(evt);
            }
        });

        CodigoTextField.setBackground(new java.awt.Color(255, 255, 255));
        CodigoTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CodigoTextField.setEnabled(false);
        CodigoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(126, 42, 12));
        jLabel12.setText("Nome do Produto");

        QuantidadeTextField.setBackground(new java.awt.Color(255, 255, 255));
        QuantidadeTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        QuantidadeTextField.setEnabled(false);
        QuantidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantidadeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(CodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(SalvarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(CancelarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(QuantidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EditarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NovoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuantidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarButton)
                    .addComponent(CancelarButton)
                    .addComponent(EditarButton)
                    .addComponent(ExcluirButton)
                    .addComponent(NovoButton))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jToolBar2.add(jPanel1);

        jToolBar3.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(255, 251, 242));
        jPanel2.setForeground(new java.awt.Color(255, 251, 242));

        ConsultaTextField.setBackground(new java.awt.Color(255, 255, 255));
        ConsultaTextField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 210, 164), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)), javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1)));
        ConsultaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaTextFieldActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(236, 14, 131));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pesquisar");
        jButton5.setToolTipText("");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ConsultaArea.setColumns(20);
        ConsultaArea.setRows(5);
        jScrollPane1.setViewportView(ConsultaArea);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(126, 42, 12));
        jLabel8.setText("Digite o Nome do Produto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsultaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ValorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTextFieldActionPerformed

    private void ConsultaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaTextFieldActionPerformed

    private void NovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoButtonActionPerformed
    HabilitarBotao(true);
    HabilitarCampos(true);
    Tipo = "novo";
    limparCampos();
    CodigoTextField.requestFocus();
    }//GEN-LAST:event_NovoButtonActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
    limparCampos();
    HabilitarBotao(false);
    HabilitarCampos(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        int linha = TabelaProdutos.getSelectedRow();
        int Confirmacao = JOptionPane.showConfirmDialog(null, "Deseja Excluir?","Confirmação",JOptionPane.YES_NO_OPTION);
        if(Confirmacao == JOptionPane.YES_OPTION){
            DefaultTableModel model = (DefaultTableModel) TabelaProdutos.getModel();
            DataBaseArrays.ArrayProdutos.remove(linha);
            model.removeRow(linha);
            LeitorEEscritor.Escrever(Path, DataBaseArrays.ArrayProdutos, new ProdutoCodec(), false);
            limparCampos();
        }// TODO add your handling code here:
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    private void SalvarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarButtonActionPerformed
        try{
            if(CodigoTextField.getText().trim().isEmpty() || ValorTextField.getText().trim().isEmpty() || CodigoTextField.getText().trim().isEmpty() || TipoComboBox.getSelectedIndex() == -1 || QuantidadeTextField.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null,"Campos Vazio, digite algo!", "Campos Vazios",JOptionPane.WARNING_MESSAGE);
            }
            else{
            
                if(Tipo.equals("novo")){
                    int Codigo = Integer.parseInt(CodigoTextField.getText().trim());
                    String Nome = NomeTextField.getText().trim();
                    Double Valor =  Double.parseDouble(ValorTextField.getText().trim());
                    String TipoProduto = (String) TipoComboBox.getSelectedItem();
                    int Quantidade = Integer.parseInt(QuantidadeTextField.getText().trim());
                    DataBaseArrays.ArrayProdutos.add(new Produtos(Codigo,Nome,TipoProduto,Valor,Quantidade));
                    LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayProdutos , new ProdutoCodec(), true);
                    carregarTabela();
                    limparCampos();
                    HabilitarBotao(false);
                    HabilitarCampos(false);
                }
                else if(Tipo.equals("editar")){
                    int linha = TabelaProdutos.getSelectedRow();
                    if(linha != -1){
                        int Codigo = Integer.parseInt(CodigoTextField.getText().trim());
                        String Nome = NomeTextField.getText().trim();
                        Double Valor =  Double.parseDouble(ValorTextField.getText().trim());
                        String TipoProduto = (String) TipoComboBox.getSelectedItem();
                        int Quantidade = Integer.parseInt(QuantidadeTextField.getText());
                        DataBaseArrays.ArrayProdutos.set(linha, new Produtos(Codigo,Nome,TipoProduto,Valor,Quantidade));
                        LeitorEEscritor.Escrever(Path,DataBaseArrays.ArrayProdutos , new ProdutoCodec(), false);
                        carregarTabela();
                        limparCampos();
                        HabilitarCampos(false);
                        HabilitarBotao(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Selecione uma linha para editar!", "Selecione uma linha",JOptionPane.WARNING_MESSAGE);
                    }
                }
            
            } 
        }catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Digite um numero válido!","ERROR: Caracter Invalido",JOptionPane.WARNING_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_SalvarButtonActionPerformed

    private void TabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaProdutosMouseClicked
        int linha = TabelaProdutos.getSelectedRow();
        if (linha != -1) {
            CodigoTextField.setText(TabelaProdutos.getValueAt(linha, 0).toString());
            NomeTextField.setText(TabelaProdutos.getValueAt(linha, 1).toString());
            TipoComboBox.setSelectedIndex(SelecionarEspecie(TabelaProdutos.getValueAt(linha,2).toString()));
            ValorTextField.setText(TabelaProdutos.getValueAt(linha, 3).toString());
            QuantidadeTextField.setText(TabelaProdutos.getValueAt(linha, 4).toString());
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaProdutosMouseClicked

    private void EditarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarButtonActionPerformed
         HabilitarBotao(true);
        HabilitarCampos(true);
        Tipo = "editar";
        CodigoTextField.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_EditarButtonActionPerformed

    private void TipoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoComboBoxActionPerformed

    private void NomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTextFieldActionPerformed

    private void CodigoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTextFieldActionPerformed

    private void QuantidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantidadeTextFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ConsultaArea.setText("");
        for(Produtos a : DataBaseArrays.ArrayProdutos){
        if(a.getNome().toLowerCase().contains(ConsultaTextField.getText())){
            ConsultaArea.setText(a.toString());
        }
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void limparCampos(){
        CodigoTextField.setText("");
        NomeTextField.setText("");
        ValorTextField.setText("");
        TipoComboBox.setSelectedIndex(-1);
        QuantidadeTextField.setText("");
    }
    
    private void HabilitarBotao(boolean a){
        SalvarButton.setVisible(a);
        CancelarButton.setVisible(a);
        NovoButton.setVisible(!a);
        EditarButton.setVisible(!a);
        ExcluirButton.setVisible(!a);
        
    }
    
    private void HabilitarCampos(boolean a){
    CodigoTextField.setEnabled(a);
    NomeTextField.setEnabled(a);
    ValorTextField.setEnabled(a);
    TipoComboBox.setEnabled(a);
    QuantidadeTextField.setEnabled(a);
    }
    
    private void carregarTabela() {
    DefaultTableModel model = (DefaultTableModel) TabelaProdutos.getModel();
    model.setRowCount(0); 

    for (Produtos c : DataBaseArrays.ArrayProdutos) {
        model.addRow(new Object[]{
            c.getCodigo(),
            c.getNome(),
            c.getTipo(),
            c.getValor(),
            c.getQuantidade()
        });
    }
}
    
    private int SelecionarEspecie(String a){
    if(a.equals("Ração")){
        return 0;
    }
    else if(a.equals("Brinquedo")){
        return 1;
    }
    else if(a.equals("Acessório")){
        return 2;
    }
    else{
        return 3;
    }
    
    }
    
  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarButton;
    private javax.swing.JTextField CodigoTextField;
    private javax.swing.JTextArea ConsultaArea;
    private javax.swing.JTextField ConsultaTextField;
    private javax.swing.JButton EditarButton;
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JButton NovoButton;
    private javax.swing.JTextField QuantidadeTextField;
    private javax.swing.JButton SalvarButton;
    private javax.swing.ButtonGroup SexoButton;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JComboBox<String> TipoComboBox;
    private javax.swing.JTextField ValorTextField;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
